apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: apps-hpa
  labels:
    app: nodejs-app-hpa
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nodejs-app-hpa
  template:
    metadata:
      labels:
        app: nodejs-app-hpa
    spec:
      containers:
      - name: nodejs-hpa
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
