apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: apps-hpa
spec:
  selector:
    app: nodejs-app-hpa
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
  type: {{ .Values.service.type }}
